CREATE TABLE STUDENT1 (ID BIGINT AUTO_INCREMENT NOT NULL, 
FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), 
PRIMARY KEY (ID))

CREATE TABLE STUDENT2 (ID BIGINT NOT NULL, BIO VARCHAR(2000), 
DATEOFBIRTH DATE, EMAIL VARCHAR(255), 
FIRSTNAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(255) NOT NULL, 
PRIMARY KEY (ID))

CREATE TABLE wohnort (ID BIGINT AUTO_INCREMENT NOT NULL, 
STRASZE VARCHAR(255), 
PRIMARY KEY (ID))

CREATE TABLE stadt (ID BIGINT NOT NULL, 
BUNDESLAND VARCHAR(255), PLZ VARCHAR(255), STADT VARCHAR(255), 
PRIMARY KEY (ID))

CREATE TABLE land (ID BIGINT NOT NULL, 
LAND VARCHAR(255), 
PRIMARY KEY (ID))


CREATE TABLE PERSON (FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255),
BIRTHDAY VARCHAR(255) NOT NULL, NUMBER VARCHAR(255) NOT NULL, P
RIMARY KEY (BIRTHDAY, NUMBER))


ALTER TABLE stadt ADD CONSTRAINT FK_stadt_ID FOREIGN KEY (ID) REFERENCES wohnort (ID)
ALTER TABLE land ADD CONSTRAINT FK_land_ID FOREIGN KEY (ID) REFERENCES wohnort (ID)
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
