ALTER TABLE stadt DROP FOREIGN KEY FK_stadt_ID
ALTER TABLE land DROP FOREIGN KEY FK_land_ID
DROP TABLE STUDENT1
DROP TABLE STUDENT2
DROP TABLE wohnort
DROP TABLE stadt
DROP TABLE land
DROP TABLE PERSON
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
